package osoc.leiedal.android.aandacht.database;

import android.content.ContentResolver;
import android.content.ContentValues;

import java.util.Random;

import osoc.leiedal.android.aandacht.contentproviders.AandachtContentProvider;
import osoc.leiedal.android.aandacht.database.model.reports.Report;

/**
 * This static class contains data and methods to generate test data. Each injection of data into
 * the database will attempt to randomly combine attributes to provide for a more realistic user
 * experience.
 * </p>
 * It should be noted that this class will clear the database before injecting newly
 * generated data.
 */
public class DummyData {

    /* ============================================================================================
        STATIC MEMBERS
    ============================================================================================ */

    public static int REPORT_COUNT = 10;
    public static int MESSAGE_COUNT = 25; // per report

    // arrays holding a status and chance for it's occurrence
    public static String[] STATUSES_LABELS = {ReportsTable.STATUS_ACTIVE, ReportsTable.STATUS_PENDING, ReportsTable.STATUS_DENIED, ReportsTable.STATUS_FINISHED};
    public static double[] STATUSES_CHANCES = {0.2, 0.2, 0.3, 1};

    // --------------------------------------------------------------------------------------------

    private static final Random rnd = new Random();

    // locations around which generated reports will be situated
    private static final double[] LOCATION_GHENT = {51.0537439, 3.7241694};
    private static final double[] LOCATION_KORTRIJK = {50.8249558, 3.2643610};

    // which location to use from the previously defined ones
    private static double[] LOCATION = LOCATION_GHENT;

    // array of address names
    private static final String[] ADDRESSES = {
            "A. Casier De Ter Bekenlaan",
            "Aaigemstraat",
            "Abdijmolenstraat",
            "Abdisstraat",
            "Achilles Musschestraat",
            "Achtenkouterstraat",
            "Adelaarsstraat",
            "Afrikalaan",
            "Afsneedorp",
            "Afsneekouter",
            "Ajuinlei",
            "Akkerhage",
            "Akkerstraat",
            "Akkerstraat 82",
            "Albrecht Rodenbachstraat",
            "Alfons Bijnlaan",
            "Alfons Van Den Broeckstr",
            "Alpacastraat",
            "Alphonse Sifferlaan",
            "Andre De Bruynstraat",
            "Antonius Triestlaan",
            "Antoon Catriestraat",
            "Antwerpenplein",
            "Antwerpenplein 13",
            "Antwerpsesteenweg",
            "Apostelhuizen",
            "Apostelhuizen 26bus",
            "Appelstraat",
            "Armand Bourdonlaan",
            "Arthur Verhaegenstraat",
            "Asselsstraat",
            "August Vermeylenstraat",
            "Autoweg-noord",
            "Avennesdreef",
            "Baarleboslaan",
            "Baarledorpstraat",
            "Bagattenstraat",
            "Baliestraat",
            "Balsamierenstraat",
            "Baudelokaai",
            "Baudelostraat",
            "Beekstraat",
            "Beekstraatkouter",
            "Beemdstraat",
            "Begijnengracht",
            "Begijnhofdries",
            "Begijnhoflaan",
            "Belfortstraat",
            "Bellevuestraat",
            "Bennesteeg",
            "Benninsbrugstraat",
            "Berouw",
            "Beukelaarstraat",
            "Beukenlaan",
            "Beverhoutplein",
            "Bevrijdingslaan",
            "Bibliotheekstraat",
            "Biekorfstraat",
            "Biezenstuk",
            "Bij Sint-jacobs",
            "Bijde Inkomststraat",
            "Bijenstraat",
            "Bijlokehof",
            "Bijlokevest",
            "Bijlokevest 153 Ba",
            "Blaisantvest",
            "Blankenbergestraat",
            "Blauwstraat",
            "Blazoenstraat",
            "Blekerijstraat",
            "Blekerijstraat 75 Kantoor 1-",
            "Blekersdijk",
            "Blijde Inkomststraat",
            "Boelenaar",
            "Bollewerkstraat",
            "Bomastraat",
            "Bomastraat 30",
            "Bommelstraat",
            "Boomstraat",
            "Borkelaarstraat",
            "Botermarkt",
            "Botestraat",
            "Brabantdam",
            "Bredestraat",
            "Breestraat",
            "Broederlijk Weversplein",
            "Broekkantstraat",
            "Brugsepoortstraat",
            "Brugsesteenweg",
            "Brugsevaart",
            "Brugstraat",
            "Bruiloftstraat",
            "Brusselsepoortstraat",
            "Brusselsepoortstraat 131-",
            "Brusselsesteenweg",
            "Buchtenstraat",
            "Buffelstraat",
            "Burggravenlaan",
            "Burggravenlaan 333-",
            "Burgstraat",
            "Busstraat",
            "Casinoplein",
            "Cataloniestraat",
            "Charles De Costerstraat",
            "Charles De Kerchovelaan",
            "Charles De Kerckhovelaan",
            "Chr. Van Der Heydenlaan",
            "Citadellaan",
            "Citadelpark",
            "Clarissenstraat",
            "Congrescentrum",
            "Congreslaan",
            "Corduwaniersstraat",
            "Coupure",
            "Coupure Links",
            "Coupure Rechts",
            "Cyriel Buyssestraat",
            "D. Kinetstraat",
            "Dampoorstraat",
            "Dampoortstraat",
            "Dampoortstraat 008-",
            "Dampoortstraat 8-",
            "Davidtenierslaan",
            "De Pintelaan",
            "Deinse Horsweg",
            "Dendermondsesteenweg",
            "Dendermondsesteenweg 140 B D",
            "Dendermondsesteenweg 41h",
            "Dendermondsesteenweg 42",
            "Derbystraat",
            "Desire Van Monckhovenstr",
            "Desteldonkdorp",
            "Dijkweg",
            "Dikkelindestraat",
            "Distelstraat",
            "Dok",
            "Dok Zuid",
            "Dok-noord",
            "Domien Geersstraat",
            "Domien Ingelsstraat",
            "Donkersteeg",
            "Doornzelestraat",
            "Doornzelestraat 27-",
            "Drabstraat",
            "Dracenastraat",
            "Dreef",
            "Driekoningenstraat",
            "Driemasterstraat",
            "Drieselstraat",
            "Drongenhof",
            "Drongenplein",
            "Drongensesteenweg",
            "Drongensteenweg",
            "Druifstraat",
            "Duddegemstraat",
            "Duivelstraat",
            "Dukkeldamstraat",
            "E3-plein",
            "Ebergiste De Deynestraat",
            "Eddastraat",
            "Edm Blockstraat",
            "Edmond Helderweirdtstraat",
            "Edmond Van Beverenplein",
            "Edmond Van Beverenplein  Myosotisstraat",
            "Eedverbondkaai",
            "Eekhout",
            "Eekhoutdriesstraat",
            "Eendrachtstraat",
            "Eikstraat",
            "Einde Were",
            "Ekkergemstraat",
            "Eksaardserijweg",
            "Elfjulistraat",
            "Elshout",
            "Elyzeese Velden",
            "Elzeboomlaan",
            "Emanuel Hielstraat",
            "Emiel Van Swedenlaan",
            "Emile Braunplein",
            "Emilius Seghersplein",
            "Eugeen Zetternamstraat",
            "Evergemsesteenweg",
            "F. Laurentplein",
            "F. Rooseveltlaan",
            "Ferdinand Lousbergskaai",
            "Filips Van Arteveldestraat",
            "Flamingostraat",
            "Fleurusstraat",
            "Florbertusstraat",
            "Forelstraat",
            "Fortlaan",
            "Fr. Ferrerlaan",
            "Fr.rooseveltlaan",
            "Francisco Ferrerlaan",
            "Francois Laurentplein",
            "Francois Laurentplein 19-",
            "Francois Van Impelaan",
            "Franklin Rooseveltlaan",
            "Franklin Rooseveltlaan 348 B D",
            "Frans Gevaertstraat",
            "Frans Louwersstraat",
            "Frans Van Ryhovelaan",
            "Fransisco Fenerlaan",
            "Fratersplein",
            "Frederik Burvenichstraat",
            "Fregatstraat",
            "Frere Orbanlaan",
            "Fresiastraat",
            "Gaaipersstraat",
            "Gaardeniersweg",
            "Gagelstraat",
            "Galgenberg",
            "Galglaan",
            "Gandastraat",
            "Ganzendries",
            "Gasmeterlaan",
            "Gaspeldoorndreef",
            "Gaverstraat",
            "Gebr. Vandeveldestraat",
            "Gebroeders De Cockstraat",
            "Gebroeders De Smetstraat",
            "Gebroeders Van De Veldestraat",
            "Gebroeders Van Eykstraat",
            "Gebroeders Vandeveldestraat",
            "Gebrs Vandeveldestraat",
            "Geelgorsstraat",
            "Geen Fysiek Adres",
            "Geitstraat",
            "Geldmunt",
            "Gentbruggekouter",
            "Gentbruggeplein",
            "Gentseaardeweg",
            "Gentsestwg",
            "Gentstraat",
            "Geo Verbancklaan",
            "Gestichtstraat",
            "Gewad",
            "Gildestraat",
            "Godshuizenlaan",
            "Goedingenstraat",
            "Goedlevenstraat",
            "Gordunakaai",
            "Goubaulaan",
            "Gouden Leeuwplein",
            "Goudenleeuwplein",
            "Gouvernementstraat",
            "Gouvernementstraat 7 Ba",
            "Gouvernementstraat A",
            "Graaf Van Vlaanderenplein",
            "Graslei",
            "Grauwpoort",
            "Grensstraat",
            "Griendijk",
            "Groendreef",
            "Groene Briel",
            "Groenespechtstraat",
            "Groenstraat",
            "Groenstraat 116 Bc",
            "Groentenmarkt",
            "Groenvinkstraat",
            "Grondwetlaan",
            "Groot-brittannielaan",
            "Grootkanonplein",
            "Grote Huidevettershoek",
            "Grotesteenweg Zuid",
            "Guldenspoorstraat",
            "Gustaaf Callierlaan",
            "Hagelandkaai",
            "Halewijnkouter",
            "Halvemaanstraat",
            "Ham",
            "Handbalstraat",
            "Harelbekestraat",
            "Haringsteeg 7-",
            "Harlekijnstraat",
            "Hazenlaan",
            "Heemstraat",
            "Heernislaan",
            "Heerweg-noord",
            "Heinakker",
            "Hemelrijkstraat",
            "Henegouwenstraat",
            "Henleykaai",
            "Henri Dunantlaan",
            "Henri Eurmanstraat",
            "Henri Farmanstraat",
            "Henri Pirennelaan",
            "Henricus Bracqstraat",
            "Herderstraat",
            "Herfststraat",
            "Herman Teirlinckstraat",
            "Hertogstraat",
            "Hipp. Persoonsstraat",
            "Hippoliet Lammensstraat",
            "Hippoliet Lippensplein",
            "Hoefslagstraatje",
            "Hoek Voldersstraat",
            "Hof Ter Mere",
            "Hofstraat",
            "Hofstraat 97-",
            "Hogeheerweg",
            "Hogeweg",
            "Holstraat",
            "Hondelee",
            "Hoogpoort",
            "Hoogstraat",
            "Hooiaard",
            "Hoornstraat",
            "Houtbriel",
            "Houtdoklaan",
            "Houtjen",
            "Hoverniersstraat",
            "Hubert Frere-orbanlaan",
            "Hubert Frore-orbanlaan",
            "Hubert Frsre-orbanlaan",
            "Hundelgemsesteenweg",
            "Hundelsgemsesteenweg",
            "Hyacinth Lippensstraat",
            "Iepenstraat",
            "Ijskelderstraat",
            "Ijzerlaan",
            "Imsakkerlaan",
            "Industriepark",
            "Industrieweg",
            "Industrieweg 122 Ab",
            "Industrieweg 122 B E",
            "Industrieweg 122 B J",
            "Industrieweg 122 B L",
            "Industrieweg 64-",
            "Industrieweg 74",
            "Industrieweg 78",
            "Ingelandgat",
            "Invalidenstraat",
            "Isegrimstraat",
            "J. Van Crombrugghestraat",
            "Jacob Van Maerlantstraat",
            "Jacobijnstraat",
            "Jakobijnenstraat",
            "Jan  Samijnstraat",
            "Jan Baptist Guinardstraat",
            "Jan Breydelstraat",
            "Jan Delvinlaan",
            "Jan Frans Willemsstraat",
            "Jan Palfijnstraat",
            "Jan Van Stopenberghestraat",
            "Jan Verspeyenstraat",
            "Jasmijnstraat",
            "Jean-baptiste D'hanedreef",
            "Jean-baptiste De Gieylaan",
            "Jef Crickstraat",
            "Jeroom Dequesnoylaan",
            "Jeruzalemstraat",
            "Joachim Schayckstraat",
            "Johan Daisnestraat",
            "Johannes Schrantstraat",
            "John Kennedylaan",
            "Joremaaie",
            "Joseph Gerardstraat",
            "Jozef Guislainstraat",
            "Jozef Ii-straat",
            "Jozef Kluyskensstraat",
            "Jozef Plateaustraat",
            "Jozef Vervaenestraat",
            "Jozef Wautersstraat",
            "Jubileumlaan",
            "Julius De Vigneplein",
            "Justus De Harduwijnlaan",
            "K. Van De Woestijnestr.",
            "Kaarderijstraat",
            "Kalandeberg",
            "Kalandestraat",
            "Kamerijkstraat",
            "Kammerstraat",
            "Kantienberg",
            "Kapelledreef",
            "Kapiteinstraat",
            "Karperstraat",
            "Kartuizerlaan",
            "Kastanjestraat",
            "Kasteellaan",
            "Kasterbant",
            "Kattenberg",
            "Kazemattenstraat",
            "Keizer Karelstraat",
            "Keizer Leopoldstraat",
            "Keizervest",
            "Kempstraat",
            "Kennedy Industriepark",
            "Kerkhofstraat",
            "Kerkstraat",
            "Ketelpoort",
            "Ketelvest",
            "Kettingstraat",
            "Keuze",
            "Kiekenbosstraat",
            "Kiekenstraat",
            "Kikvorsstraat",
            "Klapeksterstraat",
            "Kleemstraat",
            "Kleimoer",
            "Klein Turkije",
            "Kleindokkaai",
            "Kleindokkaai 3",
            "Kleine Gentstraat",
            "Kleine Vismarkt",
            "Kliniekstraat",
            "Kluisweg",
            "Kluizensesteenweg",
            "Knokkestraat",
            "Koersenstraat",
            "Koestraat",
            "Kolegemstraat",
            "Kollebloemstraat",
            "Kolveniersgang",
            "Kon. Elisabethlaan",
            "Kon. Maria Hendrikaplein",
            "Kongostraat",
            "Koning Albertlaan",
            "Koning Albertlaan 178",
            "Koning Astridlaan",
            "Koning Boudewijnstraat",
            "Koning Leopold 2 Laan",
            "Koning Leopold Ii-laan",
            "Koningin Astridlaan",
            "Koningin Elisabethlaan",
            "Koningin Fabiolalaan",
            "Koningin Maria Hendrikapl",
            "Koningin Maria Hendrikapl 5",
            "Koningin Maria Hendrikaplein",
            "Koningin Maria Hendrikaplein 5-",
            "Koninging Elisabethlaan",
            "Koningsdal",
            "Koningstraat",
            "Koolkapperstraat",
            "Koolsteeg",
            "Koophandelsplein",
            "Koopvaardijlaan",
            "Koraalwortelsraat",
            "Korenlei",
            "Korenmarkt",
            "Korhoenstraat",
            "Korianderstraat",
            "Korte Kruisstraat",
            "Korte Magerstraat",
            "Korte Meer",
            "Kortedagsteeg",
            "Kortemunt",
            "Kortrijkse Steenweg",
            "Kortrijksepoortstraat",
            "Kortrijksesteenweg",
            "Kortrijksesteenweg  H",
            "Kortrijksesteenweg 676",
            "Kortrijksesteenweg B",
            "Kortrijksesteenweg C",
            "Kortrijksestw",
            "Kouter",
            "Kouter 1 Bus",
            "Kouterdreef",
            "Kraanlei",
            "Kraanlei 27",
            "Kramersplein",
            "Krevelstraat",
            "Krijgsgasthuisstraat",
            "Krijgslaan",
            "Krijtestraat",
            "Krommehamlaan",
            "Kruitmagazijnstraat",
            "Kuiperskaai",
            "Kunstlaan",
            "Kwartelstraat",
            "Lammerstraat",
            "Land En Waaslaan",
            "Land Van Waaslaan",
            "Landegemdorp",
            "Lange Kruisstraat",
            "Lange Munt",
            "Lange Steenstraat",
            "Lange Violettestraat",
            "Langemunt",
            "Langerbruggekaai",
            "Langerbruggestraat",
            "Langerbruggestraat 76-",
            "Langezoutstraat",
            "Lavendelstraat",
            "Ledebergplein",
            "Ledebergstraat",
            "Ledergemstraat",
            "Leebeekstraat",
            "Leeuwerikstraat",
            "Leeuwstraat",
            "Leiekaai",
            "Leieriggestraat",
            "Lentestraat",
            "Leo Baeckelandstraat",
            "Leo Tertzweillaan",
            "Liefkensstraat",
            "Lievekaai",
            "Lieven Bauwensplein",
            "Lieven De Winnestraat",
            "Lijnmolenstraat",
            "Limburgstraat",
            "Lindenlei",
            "Lisdoddestraat",
            "Lochtingstraat",
            "Londenstraat",
            "Loofblommestraat",
            "Loskaai",
            "Lostraat",
            "Lothariusstraat",
            "Louis Delebecquelaan",
            "Louise Deachestraat",
            "Louise Derachestraat",
            "Lourdesstraat",
            "Lucas Munichstraat",
            "Luiklaan",
            "M Claeysplein",
            "M St. Kristoffelstraat",
            "Maaltebruggestraat",
            "Maaltekouter",
            "Mageleinstraat",
            "Mageleinstraat En Sint-baafsplein",
            "Magergoedhof",
            "Mahatma Gandhistraat",
            "Maisstraat",
            "Makelaarsstraat",
            "Makelaarstraat",
            "Manchesterstraat",
            "Marcastraat",
            "Marekstraat",
            "Maria Theresiastraat",
            "Mariakerksesteenweg",
            "Markt",
            "Marmotstraat",
            "Martelaarslaan",
            "Mechelsesteenweg",
            "Meelstraat",
            "Meerhem",
            "Meerkoetlaan",
            "Meerseniersstraat",
            "Meersstraat",
            "Meeuwstraat",
            "Meibloemstraat",
            "Mellestraat",
            "Mendonkdorp",
            "Merelbekestationplein",
            "Meulestedekaai",
            "Meulesteedsesteenweg",
            "Mimosastraat",
            "Moervaartkaai",
            "Molenaarsstraat",
            "Molenstraat",
            "Molenwalstraat",
            "Molzelebilk",
            "Molzelestraat",
            "Monterreystraat",
            "Morekstraat",
            "Mosgaverstraat",
            "Mostwegel",
            "Motorstraat",
            "Moutstraat",
            "Muidepoort",
            "Muidepoort 85-",
            "Muilaardstraat",
            "Muinkkaai",
            "Muinklaan",
            "Muizelstraat",
            "Muizelstraat 43 B A",
            "Myosotisstraat",
            "Napoleon Destanbergstraat 11",
            "Nederkouter",
            "Nederpolder",
            "Neermeerskaai",
            "Nekkersberglaan",
            "Nekkersputstraat",
            "Neuseplein",
            "New-orleansstraat",
            "New-orleansstraat 16",
            "New-yorkstraat",
            "New-yorkstraat 7",
            "Nieuwbrugkaai",
            "Nieuwe Wandeling",
            "Nieuwebosstraat",
            "Nieuwelosstraat",
            "Nieuwevaart",
            "Nieuwewandeling",
            "Nieuwland",
            "Nieuwpoort",
            "Nijverheidskaai",
            "Nonnemeersstraat",
            "Noordhoutstraat",
            "Noordstraat",
            "Normaalschool Straat",
            "Normaalschoolstraat",
            "Notarisstraat",
            "Octaaf Soudanstraat",
            "Octaaf Van Dammestraat",
            "Offerlaan",
            "Offerlaan 116-",
            "Oktrooiplein",
            "Olifantenstraat",
            "Olifantstraat",
            "Olijfstraat",
            "Onafhankelijkheidslaan",
            "Onderbergen",
            "Onderstraat",
            "Onze-lieve-vrouwdreef",
            "Ooievaarstraat",
            "Ooilamstraat",
            "Oostakkerdorp",
            "Oosteeklostraat",
            "Opgeeistenlaan",
            "Opvoedingstraat",
            "Orchideestraat",
            "Oscar De Gruyterstraat",
            "Oscar De Reusestraat",
            "Ottergemsesteenweg",
            "Ottergemsesteenweg - Zuid",
            "Ottergemsesteenweg 425-",
            "Ottergemsestwg - Zuid",
            "Ottogracht",
            "Ottregemsesteenweg Zuid",
            "Oudburg",
            "Oude Brusselseweg",
            "Oude Houtlei",
            "Oude-abdijstraat",
            "Oudebareelstraat",
            "Oudeheerweg",
            "Oudenaardsesteenweg",
            "Oudenaardsesteenweg 32 Be",
            "Oudescheldestraat",
            "Oudevest",
            "Oudewee",
            "Overpoortstraat",
            "Overzet",
            "P. De Smet De Naeyerpln",
            "P. Van Reysschootlaan",
            "Palinghuizen",
            "Pannestraat",
            "Pantserschipstraat",
            "Papegaaistraat",
            "Paradijskouter",
            "Parklaan",
            "Parkplein",
            "Part-arthurlaan",
            "Patershol-plotersgracht",
            "Patijntjesstraat",
            "Patijntjestraat",
            "Patijntjestraat 34 Ba",
            "Paul De Smet De Naeyerpl",
            "Paul Fredericqstraat",
            "Pauwstraat",
            "Peerstraat",
            "Pekelharing",
            "Pekelharing (zijstraat Coupure)",
            "Pelikaanstraat",
            "Penitentenstraat",
            "Pensmarkt",
            "Peperstraat",
            "Ph. Van Der Nootstraat",
            "Phoenixstraat",
            "Pijlkruidstraat",
            "Pijphoekstraat",
            "Pilorijnstraat",
            "Piratenstraat",
            "Pleispark",
            "Pleitstraat",
            "Plotersgracht",
            "Poel",
            "Pollepelstraat",
            "Pontstraat",
            "Poolse - Winglaan",
            "Poortakkerstraat",
            "Port Arthurlaan",
            "Posteernestraat",
            "Pr. Clementinalaan",
            "Predikherenlei",
            "Prinsenhof",
            "Prinses Clementinalaan",
            "Proeftuinstraat",
            "Prudens Van Duyseplein",
            "Puinstraat",
            "Putkapelstraat",
            "Putstraat",
            "Raapstraat",
            "Raas Van Gaverestraat",
            "Raas Van Gaverestraat 67 Bd",
            "Rabotstraat",
            "Raf Verhaeststraat",
            "Ramen",
            "Ramskapellelaan",
            "Ramstraat",
            "Rasphuisstraat",
            "Ravensteinstraat",
            "Ravenstraat",
            "Recollettenlei",
            "Reep",
            "Reigerstraat",
            "Remi Vlerickstraat",
            "Renaat De Rudderstraat",
            "Rerum-novarumplein",
            "Ridderstraat",
            "Rietorchisstraat",
            "Rijsenbergstraat",
            "Rijsvisschepark",
            "Rijvisschestraat",
            "Ringvaartweg Wondelgem",
            "Roeispaanstraat",
            "Rokerelsstraat",
            "Rondehuisjesdreef",
            "Rooigemlaan",
            "Roosakker",
            "Rozemarijnstraat",
            "Rozendaalken",
            "Rozier",
            "Ruienhovestraat",
            "Saffierstraat",
            "Sagastraat",
            "Sanderswal",
            "Sassekaai",
            "Savaanstraat",
            "Schaapsdoornstraat",
            "Schaverdijnstraat",
            "Scheeplosserstraat",
            "Scheepzatestraat",
            "Schoenerstraat",
            "Schoenlapperstraat",
            "Schooldreef",
            "Schoolkaai",
            "Schoolstraat",
            "Schoonzichtstraat",
            "Schouwburgstraat",
            "Schouwingstraat",
            "Schrijnwerkersstraat",
            "Schuurkenstraat",
            "Seminariestraat",
            "Serpentstraat",
            "Simon De Mirabellostraat",
            "Singel",
            "Sint - Rochusstraat",
            "Sint Markoenstraat",
            "Sint Paulusstraat",
            "Sint Pietersaalstraat",
            "Sint-amandplein",
            "Sint-amandsstraat",
            "Sint-amandstraat",
            "Sint-annaplein",
            "Sint-antoniuskaai",
            "Sint-baafsplein",
            "Sint-bernadettestraat",
            "Sint-clarastraat",
            "Sint-denijslaan",
            "Sint-dionysiusstraat",
            "Sint-eligiusstraat",
            "Sint-elisabethplein",
            "Sint-godelievestraat",
            "Sint-jacobsnieuwstraat",
            "Sint-jan-baptiststraat",
            "Sint-joriskaai",
            "Sint-jozefstraat",
            "Sint-katelijnestraat",
            "Sint-kristoffelstraat",
            "Sint-kwintensberg",
            "Sint-lievenslaan",
            "Sint-lievenspoortstraat",
            "Sint-margrietstraat",
            "Sint-martensstraat",
            "Sint-michielshelling",
            "Sint-michielsplein",
            "Sint-michielsstraat",
            "Sint-niklaas",
            "Sint-niklaasstraat",
            "Sint-pietersaalststraat",
            "Sint-pietersnieuwstraat",
            "Sint-pietersplein",
            "Sint-rochusplein",
            "Sint-salvatorstraat",
            "Sint-sebastiaanstraat",
            "Sint-simonstraat",
            "Sint-theresiastraat",
            "Sint-veerleplein",
            "Sint-widostraat",
            "Skaldenstraat",
            "Slachthuisstraat",
            "Sleepsmunt",
            "Sleepstraat",
            "Sleepstraat 215",
            "Sleepstraat 88",
            "Sloepstraat",
            "Slotendries",
            "Sluizeken",
            "Sluizekenstraat",
            "Smalleheerweg",
            "Smidsestraat",
            "Snepkaai",
            "Sneppenbrugstraat",
            "Soenenspark",
            "Sony Pietersnieuwstraat",
            "Sophie Van Akenstraat 48-",
            "Sparrestraat",
            "Speelmanstraat",
            "Speistraat",
            "Spijkstraat",
            "Spinmolenplein",
            "Spitaalpoortstraat",
            "Sportstraat",
            "St Kristoffelstraat",
            "St-Pietersaalststraat",
            "St-baafsplein",
            "St-salvatorstraat",
            "St-Bernadettestraat",
            "St-rochusplein",
            "Staakskenstraat",
            "Stapelplein",
            "Steenakker",
            "Steendam",
            "Steenhuisdreef",
            "Steenweg",
            "Steltloperstraat",
            "Stoppelstraat",
            "Stropkaai",
            "Stropstraat",
            "Takkebosstraat",
            "Tapuitstraat",
            "Tempelhof",
            "Tenderstraat",
            "Tennisbaanstraat",
            "Tentoonstellingslaan",
            "Ter Platen",
            "Ternesselei",
            "Terneuzenlaan",
            "Tinkstraat",
            "Tinnenpotstraat",
            "Toemaattragel",
            "Tolhuislaan",
            "Tortelduifstraat",
            "Trekweg",
            "Trommelstraat",
            "Tuinlaan",
            "Tuinwijklaan",
            "Twaalfapostelenstraat",
            "Twaalfkameren",
            "Tweebruggenstraat",
            "Uitvangstraat",
            "Vaderlandstraat",
            "Van Beverenplein",
            "Vanillestraat",
            "Varendriesstraat",
            "Varenstraat",
            "Veenakkerstraat",
            "Veldestraat",
            "Veldstraat",
            "Veldstraat 69",
            "Velostraat",
            "Vennestraat",
            "Verenigde - Natieslaan",
            "Verlorenkost",
            "Verlorensteenstraat",
            "Verpleegstersstraat",
            "Ververijstraat",
            "Victor Braeckmanlaan",
            "Victor Frisstraat",
            "Victoriastraat",
            "Vierweegsestraat",
            "Vijfwindgatenstraat",
            "Vijvermeerspark",
            "Vina Bovypark",
            "Visserij",
            "Visserij 161 Bc",
            "Vlaamsekaai",
            "Vlaanderenstraat",
            "Vlaanderenstraat 98",
            "Vlasmarkt",
            "Vliegtuiglaan",
            "Vlinderstraat",
            "Vogelenzang",
            "Vogelmarkt",
            "Voldersstraat",
            "Volderstraat",
            "Volmolenstraat",
            "Voorhavenlaan",
            "Voorhoutkaai",
            "Voormuide",
            "Vorkstraat",
            "Voskenslaan",
            "Vossenbergstraat",
            "Vrijdagmarkt",
            "Vrijheidslaan",
            "Vroonstallestraat",
            "Vrouwebroersstraat",
            "Vrouwenstraat",
            "Waaistraat",
            "Waalbrugstraat",
            "Wallekensstraat",
            "Walpoortstraat",
            "Walstraat",
            "Warmoezeniersweg",
            "Waterhoenlaan",
            "Waterlelielaan",
            "Watermuntstraat",
            "Waterstraat",
            "Watlingtonstraat",
            "Wazenaarstraat",
            "Wellingstraat",
            "Werkhuizenstraat",
            "Werkstraat",
            "Westergemstraat",
            "Weverstraat",
            "Wiedauwkaai",
            "Wiedauwkaai 98",
            "Wielewaalstraat",
            "Wiemersdreef",
            "Wijdebroeken",
            "Wijngaardstraat",
            "Wijzemanstraat",
            "Wildebrake",
            "Wilgetronkstraat",
            "Willem Tellstraat",
            "Willem Van Nassaustraat",
            "Wintertuinstraat",
            "Witbakkerstraat",
            "Wittelinkstraat",
            "Wittepaalstraat",
            "Wittewalle",
            "Woeringenstraat",
            "Woestijnegoedlaan",
            "Wolfputstraat",
            "Wolfstraat",
            "Wolterslaan",
            "Wondelgemkaai",
            "Wondelgemstraat",
            "Woodrow Wilsonplein",
            "Wulverdam",
            "Yachtdreef",
            "Zalmstraat",
            "Zandberg",
            "Zandpoortstraat",
            "Zangvogellaan",
            "Zebrastraat",
            "Zeeschipstraat",
            "Zeilschipstraat 30 Bis",
            "Zieklien",
            "Zilverenberg",
            "Zilverhof",
            "Zinniastraat",
            "Zonnebloemstraat",
            "Zonnestraat",
            "Zuiddokweg",
            "Zuiderlaan",
            "Zuiderlaan 1",
            "Zuiderstationstraat",
            "Zuidkaai",
            "Zuidstationstraat",
            "Zuidstationstraat 31",
            "Zwaanstraat",
            "Zwartezustersstraat",
            "Zwembadstraat",
            "Zwijnaardsesteenweg",
    };

    // list of pieces of text with different lengths
    private static final String[] DESCRIPTION = {
            "Kind verloren gelopen. Klein meisje van 6 jaar oud met roze jas en Hello Kitty rugzak.",
            "Auto versperd belangrijke nooduitgang.",
            "Rook gesignaleerd op bovenste verdieping. Meld visuele bevestiging, neem geen verdere acties!",
            "Persoon flauwgevallen, blijft buiten bewustzijn.",
            "Rode herenfiets gestolen, dader op weg in zuidelijke richting.",
            "Personen gesignaleerd op verboden terrein.",
            "Persoon gesignaleerd op dak van het gebouw.",
            "Bouwvakkers veroorzaken geluidshinder en overlast.",
            "Signalisatie van sluikstorting.",
            "Grote barst aan hoek van het gebouw.",
            "Mogelijke gezochte persoon gesignaleerd, visuele bevestiging nodig. Neem geen persoonlijk contact op!",
            "Verboden vuurwerk afgeschoten. Extra getuigen nodig.",
            "Burenruzie escaleert op straat. Probeer personen te kalmeren en vermijdt het gebruik van wapens.",
            "Ruzie tussen marktkramers, probeer betrokkenen te kalmeren tot de politie op de plaats aankomt.",
            "Jongeren met illegale softdrugs gesignaleerd.",
            "Jongeren vallen toeristen lastig.",
            "Auto versperd de weg maar is onbruikbaar. Hulp nodig bij het verplaatsen.",
            "Vrachtwagen is halve lading voetballen verloren, weg moet vrijgemaakt worden.",
            "Jongeren hebben meerdere malen vals geld proberen te gebruiken. Ze verplaatsen zich noordwaarts.",
            "Licht auto-ongeval met blikschade. Kalmeer betrokkenen en biedt eerste hulp.",
            "Fietsongeval met lichte verwonding. Kalmeer betrokkenen en biedt eerste hulp.",
            "Persoon gesignaleerd met illegaal wapen. Hou visueel contact maar vermijdt escalatie.",
            "Persoon dreigt met zelfmoord. Hou visueel contact en probeer omstaanders te kalmeren.",
    };

    /* ============================================================================================
        STATIC METHODS
    ============================================================================================ */

    /**
     * This will delete all records from the database and then fill it again with generated
     * test data.
     *
     * @param cr the ContentResolver to access the database
     */
    public static void InjectDummyData(ContentResolver cr) {
        System.out.println("[DummyData] InjectDummyData(" + cr + ")");

        // delete old data
        cr.delete(AandachtContentProvider.CONTENT_URI_REPORTS, null, null);
        cr.delete(AandachtContentProvider.CONTENT_URI_MESSAGES, null, null);

        ContentValues[] reports = new ContentValues[REPORT_COUNT];
        // ContentValues[] messages = new ContentValues[MESSAGE_COUNT];
        for (int i = 0; i < REPORT_COUNT; i++) {
            reports[i] = Report().getContentValues();
            /*
            Generate messages here
             */
        }
        cr.bulkInsert(AandachtContentProvider.CONTENT_URI_REPORTS, reports);
    }

    /**
     * This will insert a single report into the database without any messages linked to it. This
     * is used by the notification services.
     *
     * @param cr the ContentResolver to access the database
     * @param r  the Report to insert into the database
     */
    public static void injectReport(ContentResolver cr, Report r) {
        System.out.println("[DummyData] InjectReport(" + cr + ")");
        cr.insert(AandachtContentProvider.CONTENT_URI_REPORTS, r.getContentValues());
    }

    // --------------------------------------------------------------------------------------------

    private static Report Report() {
        return new Report(
                Description(),
                Address(),
                Latitude(),
                Longitude(),
                Status(),
                TimeStart(),
                TimeEnd()
        );
    }

    private static String Description() {
        return DESCRIPTION[rnd.nextInt(DESCRIPTION.length)];
    }

    private static String Address() {
        return ADDRESSES[rnd.nextInt(ADDRESSES.length)];
    }

    private static double Latitude() {
        return LOCATION[0] + rnd.nextDouble() * 0.008 - 0.004;
    }

    private static double Longitude() {
        return LOCATION[1] + rnd.nextDouble() * 0.008 - 0.004;
    }

    private static String Status() {
        double r = rnd.nextDouble();
        double c = 0;
        for (int i = 0; i < STATUSES_LABELS.length; i++) {
            c += STATUSES_CHANCES[i];
            if (r <= c) {
                return STATUSES_LABELS[i];
            }
        }
        return STATUSES_LABELS[STATUSES_LABELS.length - 1];
    }

    private static long TimeStart() {
        final long curr = System.currentTimeMillis();
        return (curr / 1000) - rnd.nextInt(600);
    }

    private static long TimeEnd() {
        final long curr = System.currentTimeMillis();
        return (curr / 1000) + rnd.nextInt(3600);
    }

}
